# config.yml

backend:
  name: github
  repo: El-Ancla/elancla.cc
  branch: main # Branch to update (optional; defaults to master)
media_folder: "assets/uploads"
collections:
  - name: "blog"
    label: "Blog"
    folder: "_posts/"
    fields:
      - { name: Title }
